In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
df = pd.read_csv("Speed Dating Data.csv", encoding="cp1252")

In [8]:
pd.options.display.max_columns = 200

In [9]:
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [14]:
columns = list(df.columns.values)

In [15]:
import re

In [25]:
match_result = re.match(r"[^\d]+(\d_\d)", "attr1_2")
match_result.groups()

('1_2',)

In [26]:
persondf = df.drop_duplicates("iid").set_index("iid")

In [27]:
len(persondf.index)

551

In [28]:
persondf.head()

,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
iid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,2.0,0,3,1,1,10,3,NaN,10,1,11.0,0,0.29,1,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,8.0,7.0,6.0,9.0,7.0,4.0,7.0,2.0,2.0,24.0,law,1.0,NaN,NaN,NaN,2.0,2.0,5.0,Alabama,"35,223","65,929.00",1.0,5.0,1.0,law,NaN,3.0,2.0,7.0,10.0,8.0,6.0,3.0,5.0,8.0,10.0,1.0,9.0,8.0,7.0,8.0,3.0,1.0,4.0,5.0,45.0,5.0,25.0,20.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,65.0,0.0,10.0,25.0,0.0,0.0,7.0,5.0,10.0,8.0,3.0,NaN,NaN,NaN,NaN,NaN,0,5.0,7.0,8.0,4.0,6.0,3.0,6.0,4.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.92,18.92,21.62,27.03,5.41,8.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,8.0,9.0,4.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,30.0,5.0,40.0,15.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,6.0,9.0,9.0,4.0,NaN,NaN,NaN,NaN,NaN
3,3.0,0,5,1,1,10,9,NaN,6,1,11.0,0,-0.24,1,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,7.0,8.0,6.0,5.0,8.0,4.0,5.0,2.0,1.0,25.0,Economics,2.0,NaN,NaN,NaN,2.0,8.0,4.0,Connecticut,"6,268",NaN,6.0,3.0,1.0,Economist,NaN,3.0,8.0,7.0,8.0,5.0,5.0,8.0,4.0,5.0,7.0,8.0,7.0,7.0,7.0,5.0,8.0,7.0,4.0,2.0,35.0,10.0,35.0,10.0,10.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,50.0,0.0,20.0,30.0,0.0,0.0,8.0,9.0,8.0,9.0,8.0,NaN,NaN,NaN,NaN,NaN,0,7.0,9.0,10.0,7.0,8.0,9.0,8.0,7.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,0,7,1,1,10,6,NaN,3,1,11.0,0,-0.18,1,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,7.0,8.0,7.0,7.0,5.0,6.0,3.0,2.0,23.0,Law,1.0,NaN,NaN,NaN,2.0,1.0,1.0,Texas,"77,096","37,754.00",1.0,5.0,1.0,lawyer/policy work,1.0,1.0,1.0,6.0,7.0,6.0,7.0,7.0,5.0,7.0,7.0,7.0,9.0,7.0,8.0,7.0,1.0,8.0,1.0,2.0,20.0,20.0,20.0,20.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,30.0,10.0,15.0,30.0,5.0,10.0,7.0,8.0,9.0,7.0,8.0,NaN,NaN,NaN,NaN,NaN,0,4.0,10.0,8.0,5.0,8.0,7.0,6.0,7.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,24.14,13.79,20.69,27.59,10.34,3.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,8.0,7.0,8.0,6.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,20.0,20.0,20.0,20.0,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,6.0,8.0,5.0,NaN,NaN,NaN,NaN,NaN
5,5.0,0,9,1,1,10,4,NaN,1,1,11.0,0,-0.43,1,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,7.0,6.0,6.0,5.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,2.0,8.0,1.0,Bowdoin College,"94,022","86,340.00",2.0,4.0,1.0,lawyer,1.0,7.0,4.0,7.0,7.0,6.0,8.0,6.0,6.0,8.0,6.0,8.0,6.0,6.0,3.0,7.0,8.0,3.0,7.0,10.0,20.0,5.0,25.0,25.0,10.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,50.0,10.0,10.0,20.0,5.0,5.0,6.0,3.0,6.0,10.0,8.0,NaN,NaN,NaN,NaN,NaN,0,5.0,8.0,8.0,2.0,2.0,2.0,7.0,5.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,15.79,13.16,18.42,15.79,15.79,21.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,9.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,30.0,10.0,20.0,20.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,5.0,10.0,6.0,10.0,NaN,NaN,NaN,NaN,NaN

In [212]:
matchdf = df[["iid", "pid", "match"]]

In [213]:
matchdf.head()

   iid   pid  match
0    1  11.0      0
1    1  12.0      0
2    1  13.0      1
3    1  14.0      1
4    1  15.0      1

In [226]:
match_amount = len(matchdf.index)

train_size = int(match_amount * 0.8)
test_size = match_amount - train_size
batch_count = 10
batch_size = int(train_size / batch_count)

print(train_size, test_size, batch_size)

6702 1676 670

In [221]:
train_data = matchdf.iloc[:train_size, :]
test_data = matchdf.iloc[train_size:, :]

In [61]:
from sklearn.decomposition import PCA

In [85]:
feature_columns = ['age', 'race', 'imprace', 'imprelig', 'income',
                   'goal', 'date', 'go_out', 'career_c',
                   'sports', 'tvsports', 'exercise', 'dining', 'museums',
                   'art', 'hiking', 'gaming', 'clubbing', 'reading',
                   'tv', 'theater', 'movies', 'concerts', 'music',
                   'shopping', 'yoga', 'exphappy', 'expnum', 
                   'attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1',
                   'attr2_1', 'sinc2_1', 'intel2_1', 'fun2_1', 'amb2_1', 'shar2_1',
                   'attr3_1', 'sinc3_1', 'fun3_1', 'intel3_1', 'amb3_1',]

In [73]:
def check_columns(columns, newColumn):
    persondf[newColumn] = 0
    for column in columns:
        persondf[newColumn] += persondf[column]
    print(persondf[newColumn].value_counts())
    print(persondf[newColumn].describe())

In [74]:
wave1_1_columns = ['attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1', 'shar1_1',]
check_columns(wave1_1_columns, "1_1_values")

100.00    466
100.01     15
99.99      14
100.01     10
100.02      6
100.00      6
99.99       5
90.00       4
100.02      3
100.00      3
99.98       2
120.00      2
110.00      1
101.00      1
99.99       1
95.00       1
148.00      1
Name: 1_1_values, dtype: int64
count    541.000000
mean     100.100166
std        2.590789
min       90.000000
25%             NaN
50%             NaN
75%             NaN
max      148.000000
Name: 1_1_values, dtype: float64

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

In [69]:
persondf[["wave", "1_1_values"] + wave1_1_columns][persondf["1_1_values"] > 120]

     wave  1_1_values  attr1_1  sinc1_1  intel1_1  fun1_1  amb1_1  shar1_1
iid
66      3       148.0     20.0     25.0      15.0    15.0    53.0     20.0

In [75]:
wave2_1_columns = ['attr2_1', 'sinc2_1', 'intel2_1', 'fun2_1', 'amb2_1', 'shar2_1',]
check_columns(wave2_1_columns, "2_1_values")

100.00    458
100.02     13
100.01     11
99.99      10
100.01      9
100.00      7
110.00      6
99.99       6
90.00       4
105.00      4
95.00       3
100.02      3
99.99       2
99.98       1
101.00      1
100.00      1
100.02      1
100.03      1
80.00       1
112.00      1
Name: 2_1_values, dtype: int64
count    543.000000
mean     100.033831
std        1.781097
min       80.000000
25%             NaN
50%             NaN
75%             NaN
max      112.000000
Name: 2_1_values, dtype: float64

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

In [76]:
wave3_1_columns = ['attr3_1', 'sinc3_1', 'fun3_1', 'intel3_1', 'amb3_1',]
check_columns(wave3_1_columns, "3_1_values")

40.0    59
42.0    53
41.0    45
39.0    44
37.0    41
38.0    41
35.0    31
36.0    30
43.0    29
45.0    25
33.0    20
44.0    20
46.0    19
34.0    16
32.0    14
31.0    10
30.0    10
50.0     7
48.0     7
47.0     5
29.0     5
25.0     3
49.0     2
28.0     2
26.0     1
24.0     1
23.0     1
18.0     1
Name: 3_1_values, dtype: int64
count    542.000000
mean      39.042435
std        4.727710
min       18.000000
25%             NaN
50%             NaN
75%             NaN
max       50.000000
Name: 3_1_values, dtype: float64

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

In [80]:
wave5_1_columns = ['attr5_1', 'sinc5_1', 'intel5_1', 'fun5_1', 'amb5_1',]
check_columns(wave5_1_columns, "5_1_values")

42.0    35
36.0    25
41.0    25
40.0    23
39.0    21
37.0    19
38.0    18
35.0    17
34.0    16
32.0    14
45.0    12
44.0    12
43.0    10
30.0    10
31.0     9
33.0     9
46.0     6
48.0     6
50.0     5
47.0     5
29.0     3
27.0     3
26.0     3
25.0     3
28.0     2
18.0     2
22.0     1
Name: 5_1_values, dtype: int64
count    314.000000
mean      38.108280
std        5.483731
min       18.000000
25%             NaN
50%             NaN
75%             NaN
max       50.000000
Name: 5_1_values, dtype: float64

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

In [123]:
feature_df = persondf[feature_columns].copy()

In [87]:
feature_df.head()

,age,race,imprace,imprelig,income,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1
iid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,21.0,4.0,2.0,4.0,"69,487.00",2.0,7.0,1.0,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0
2,24.0,2.0,2.0,5.0,"65,929.00",1.0,5.0,1.0,NaN,3.0,2.0,7.0,10.0,8.0,6.0,3.0,5.0,8.0,10.0,1.0,9.0,8.0,7.0,8.0,3.0,1.0,4.0,5.0,45.0,5.0,25.0,20.0,0.0,5.0,65.0,0.0,10.0,25.0,0.0,0.0,7.0,5.0,10.0,8.0,3.0
3,25.0,2.0,8.0,4.0,NaN,6.0,3.0,1.0,NaN,3.0,8.0,7.0,8.0,5.0,5.0,8.0,4.0,5.0,7.0,8.0,7.0,7.0,7.0,5.0,8.0,7.0,4.0,2.0,35.0,10.0,35.0,10.0,10.0,0.0,50.0,0.0,20.0,30.0,0.0,0.0,8.0,9.0,8.0,9.0,8.0
4,23.0,2.0,1.0,1.0,"37,754.00",1.0,5.0,1.0,1.0,1.0,1.0,6.0,7.0,6.0,7.0,7.0,5.0,7.0,7.0,7.0,9.0,7.0,8.0,7.0,1.0,8.0,1.0,2.0,20.0,20.0,20.0,20.0,10.0,10.0,30.0,10.0,15.0,30.0,5.0,10.0,7.0,8.0,9.0,7.0,8.0
5,21.0,2.0,8.0,1.0,"86,340.00",2.0,4.0,1.0,1.0,7.0,4.0,7.0,7.0,6.0,8.0,6.0,6.0,8.0,6.0,8.0,6.0,6.0,3.0,7.0,8.0,3.0,7.0,10.0,20.0,5.0,25.0,25.0,10.0,15.0,50.0,10.0,10.0,20.0,5.0,5.0,6.0,3.0,6.0,10.0,8.0

In [174]:
pca = PCA(n_components="mle")

In [91]:
feature_df.dtypes

age         float64
race        float64
imprace     float64
imprelig    float64
income       object
goal        float64
date        float64
go_out      float64
career_c    float64
sports      float64
tvsports    float64
exercise    float64
dining      float64
museums     float64
art         float64
hiking      float64
gaming      float64
clubbing    float64
reading     float64
tv          float64
theater     float64
movies      float64
concerts    float64
music       float64
shopping    float64
yoga        float64
exphappy    float64
expnum      float64
attr1_1     float64
sinc1_1     float64
intel1_1    float64
fun1_1      float64
amb1_1      float64
shar1_1     float64
attr2_1     float64
sinc2_1     float64
intel2_1    float64
fun2_1      float64
amb2_1      float64
shar2_1     float64
attr3_1     float64
sinc3_1     float64
fun3_1      float64
intel3_1    float64
amb3_1      float64
dtype: object

In [113]:
feature_df["age"].median()

26.0

In [132]:
feature_df["income"] = feature_df["income"].apply(lambda x: x.replace(',', '') if type(x) is str else x)

feature_df["income"] = feature_df["income"].fillna(feature_df["income"].median()).astype("float64")

In [135]:
feature_df.describe()

C:\Users\Administrator\Anaconda3\lib\site-packages\numpy\lib\function_base.py:4116: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

,age,race,imprace,imprelig,income,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1
count,543.000000,545.000000,544.000000,544.000000,551.000000,544.000000,543.000000,544.000000,539.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,544.000000,543.000000,126.000000,544.000000,544.000000,544.000000,543.000000,542.000000,541.000000,544.000000,544.000000,544.000000,544.000000,543.000000,543.000000,542.000000,542.000000,542.000000,542.000000,542.000000
mean,26.359116,2.800000,3.733456,3.582721,44256.286751,2.148897,4.983425,2.143382,5.250464,6.395221,4.549632,6.286765,7.775735,6.972426,6.689338,5.757353,3.840074,5.751838,7.647059,5.325368,6.761029,7.898897,6.843750,7.875000,5.604779,4.415441,5.519337,5.888889,22.685478,17.290754,20.170478,17.451363,10.806476,11.832126,30.248033,13.226581,14.426048,18.527684,11.760074,11.888821,7.092251,8.285978,7.701107,8.385609,7.577491
std,3.766960,1.253818,2.842181,2.784553,12702.384591,1.448273,1.468520,1.104833,3.312471,2.630753,2.801164,2.449965,1.778032,2.059245,2.273435,2.566239,2.610746,2.485871,2.002869,2.539344,2.273611,1.720550,2.154151,1.788803,2.615307,2.757915,1.729677,5.127529,12.971917,7.204724,6.878993,6.190985,6.229105,6.474104,15.957520,6.939553,6.240256,6.653838,6.804952,6.070590,1.390081,1.412038,1.547510,1.089700,1.786293
min,18.000000,1.000000,0.000000,1.000000,8607.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000
25%,NaN,NaN,NaN,NaN,42774.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,43185.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,43650.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,55.000000,6.000000,10.000000,10.000000,109031.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [143]:
pd.isnull(feature_df.iloc[:, 0:2]).any(1).nonzero()[0]

array([ 57,  58, 127, 134, 337, 338, 344, 510], dtype=int64)

In [146]:
feature_df = feature_df.fillna(feature_df.mean())

In [155]:
def check_null():
    (index, col) = np.where(feature_df.isnull())
    for pos in zip(index, col):
        print(pos)
check_null()

(2, 45)
(7, 45)
(8, 45)
(10, 45)
(12, 45)
(15, 45)
(18, 45)
(19, 45)
(20, 45)
(22, 45)
(27, 45)
(29, 45)
(31, 45)
(33, 45)
(35, 45)
(40, 45)
(42, 45)
(43, 45)
(44, 45)
(45, 45)
(46, 45)
(47, 45)
(52, 45)
(56, 45)
(57, 45)
(58, 45)
(59, 45)
(64, 45)
(65, 45)
(68, 45)
(71, 45)
(72, 45)
(73, 45)
(78, 45)
(79, 45)
(82, 45)
(83, 45)
(86, 45)
(88, 45)
(89, 45)
(92, 45)
(93, 45)
(95, 45)
(99, 45)
(100, 45)
(101, 45)
(107, 45)
(108, 45)
(110, 45)
(111, 45)
(113, 45)
(115, 45)
(117, 45)
(125, 45)
(126, 45)
(127, 45)
(128, 45)
(131, 45)
(133, 45)
(134, 45)
(137, 45)
(138, 45)
(139, 45)
(141, 45)
(146, 45)
(149, 45)
(150, 45)
(151, 45)
(157, 45)
(160, 45)
(168, 45)
(169, 45)
(170, 45)
(171, 45)
(174, 45)
(176, 45)
(178, 45)
(180, 45)
(181, 45)
(183, 45)
(185, 45)
(187, 45)
(188, 45)
(189, 45)
(194, 45)
(196, 45)
(199, 45)
(203, 45)
(204, 45)
(205, 45)
(209, 45)
(211, 45)
(216, 45)
(217, 45)
(218, 45)
(219, 45)
(220, 45)
(222, 45)
(223, 45)
(226, 45)
(233, 45)
(237, 45)
(240, 45)
(241, 45)
(242, 45)
(243, 45)
(245, 45)
(247, 45)
(248, 45)
(249, 45)
(250, 45)
(251, 45)
(258, 45)
(260, 45)
(264, 45)
(265, 45)
(267, 45)
(268, 45)
(271, 45)
(272, 45)
(273, 45)
(275, 45)
(276, 45)
(278, 45)
(279, 45)
(280, 45)
(281, 45)
(282, 45)
(283, 45)
(284, 45)
(285, 45)
(288, 45)
(289, 45)
(291, 45)
(292, 45)
(299, 45)
(303, 45)
(304, 45)
(306, 45)
(311, 45)
(312, 45)
(313, 45)
(315, 45)
(316, 45)
(317, 45)
(319, 45)
(320, 45)
(321, 45)
(322, 45)
(323, 45)
(324, 45)
(325, 45)
(326, 45)
(327, 45)
(328, 45)
(329, 45)
(330, 45)
(331, 45)
(332, 45)
(333, 45)
(334, 45)
(335, 45)
(336, 45)
(337, 45)
(338, 45)
(339, 45)
(340, 45)
(344, 45)
(348, 45)
(349, 45)
(350, 45)
(351, 45)
(353, 45)
(358, 45)
(360, 45)
(362, 45)
(363, 45)
(364, 45)
(365, 45)
(366, 45)
(371, 45)
(372, 45)
(373, 45)
(375, 45)
(378, 45)
(379, 45)
(381, 45)
(382, 45)
(385, 45)
(388, 45)
(395, 45)
(396, 45)
(398, 45)
(399, 45)
(400, 45)
(401, 45)
(402, 45)
(404, 45)
(405, 45)
(406, 45)
(407, 45)
(410, 45)
(411, 45)
(415, 45)
(421, 45)
(422, 45)
(424, 45)
(429, 45)
(433, 45)
(434, 45)
(438, 45)
(439, 45)
(440, 45)
(444, 45)
(445, 45)
(448, 45)
(449, 45)
(450, 45)
(451, 45)
(453, 45)
(454, 45)
(456, 45)
(459, 45)
(460, 45)
(461, 45)
(462, 45)
(467, 45)
(469, 45)
(470, 45)
(471, 45)
(475, 45)
(476, 45)
(478, 45)
(481, 45)
(483, 45)
(484, 45)
(485, 45)
(486, 45)
(487, 45)
(488, 45)
(489, 45)
(491, 45)
(495, 45)
(500, 45)
(503, 45)
(507, 45)
(508, 45)
(509, 45)
(510, 45)
(515, 45)
(517, 45)
(521, 45)
(524, 45)
(527, 45)
(528, 45)
(529, 45)
(531, 45)
(532, 45)
(534, 45)
(536, 45)
(537, 45)
(538, 45)
(539, 45)
(540, 45)
(544, 45)
(545, 45)
(546, 45)
(547, 45)
(548, 45)
(550, 45)

In [159]:
feature_df = feature_df.drop("income_num", axis=1)

In [175]:
pca.fit(feature_df)

PCA(copy=True, n_components='mle', whiten=False)

In [176]:
newData = pca.fit_transform(feature_df)

In [177]:
type(newData)

numpy.ndarray

In [178]:
newData.shape

(551, 42)

In [179]:
feature_df.shape

(551, 45)

In [180]:
inverse_data = pd.DataFrame(pca.inverse_transform(newData))

In [181]:
inverse_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44
0,20.992003,3.994786,1.991328,4.003093,69486.999999,2.025499,6.989515,0.979871,5.233854,8.988256,1.998933,7.998366,8.993245,1.255589,0.803984,4.994401,1.007429,4.999986,5.975166,9.003749,0.971918,10.032042,9.993689,9.000290,7.988505,1.003018,3.003805,1.997920,15.031934,20.029006,20.030287,15.031756,15.019271,15.038372,34.889776,19.890378,14.892457,19.888713,4.889092,4.890532,6.083397,8.018957,8.006173,7.727519,7.069829
1,23.992718,2.111834,2.029426,5.029266,65928.999993,1.059640,4.986681,1.014178,5.233381,3.036927,2.037081,6.975110,10.133295,7.172067,6.684627,2.983022,5.007830,7.976033,10.111086,0.947906,9.031549,8.020938,6.960983,7.994786,3.005182,0.971835,3.974660,5.033483,45.015834,5.024045,25.033467,20.023594,0.002897,5.034469,64.955097,-0.052615,9.953035,24.958135,-0.021052,-0.051562,7.233570,5.068405,9.884436,7.560778,3.037426
2,24.995577,1.991683,7.990066,3.998187,43185.000000,5.998006,3.003237,0.959745,5.244912,2.983353,8.001424,7.007852,7.976692,5.203512,4.843706,8.002457,3.994191,5.009674,6.970836,8.010003,6.988660,7.009784,6.986506,5.024310,8.001952,7.006220,4.009768,1.995157,35.033599,10.029663,35.028868,10.031697,10.025866,0.032427,49.882369,-0.116077,19.883545,29.881175,-0.119745,-0.114924,7.976286,9.001488,8.008271,8.965528,8.020632
3,23.011126,1.974933,0.991166,0.981249,37754.000002,0.909717,5.043145,0.933274,1.034654,0.978507,1.002696,6.032560,6.930145,5.977948,7.009657,7.026610,4.958729,7.033257,6.968927,7.026761,9.044513,6.931865,7.982132,7.075304,1.039720,8.014027,1.022320,1.986738,20.006808,20.002250,19.994704,20.000407,10.022347,9.981464,29.970054,9.974100,14.965969,29.969120,4.962370,9.977081,6.646232,7.938912,9.022550,7.765323,7.850457
4,20.970278,1.971407,7.995469,1.030071,86340.000000,2.221752,3.881419,1.171605,0.906467,7.024130,3.958865,6.926649,7.081780,6.919044,7.272317,5.935032,6.116524,7.924588,5.980087,7.970138,5.829312,6.194790,3.083372,6.786018,7.874520,2.985614,6.959407,10.007911,19.981570,4.986139,25.000342,24.993213,9.941790,15.041798,50.073720,10.069079,10.088698,20.073237,5.074621,5.059563,6.861097,3.126055,6.039662,8.034479,8.434829

In [182]:
feature_df.head()

,age,race,imprace,imprelig,income,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1
iid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,21.0,4.0,2.0,4.0,69487.0,2.0,7.0,1.0,5.250464,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0
2,24.0,2.0,2.0,5.0,65929.0,1.0,5.0,1.0,5.250464,3.0,2.0,7.0,10.0,8.0,6.0,3.0,5.0,8.0,10.0,1.0,9.0,8.0,7.0,8.0,3.0,1.0,4.0,5.0,45.0,5.0,25.0,20.0,0.0,5.0,65.0,0.0,10.0,25.0,0.0,0.0,7.0,5.0,10.0,8.0,3.0
3,25.0,2.0,8.0,4.0,43185.0,6.0,3.0,1.0,5.250464,3.0,8.0,7.0,8.0,5.0,5.0,8.0,4.0,5.0,7.0,8.0,7.0,7.0,7.0,5.0,8.0,7.0,4.0,2.0,35.0,10.0,35.0,10.0,10.0,0.0,50.0,0.0,20.0,30.0,0.0,0.0,8.0,9.0,8.0,9.0,8.0
4,23.0,2.0,1.0,1.0,37754.0,1.0,5.0,1.0,1.000000,1.0,1.0,6.0,7.0,6.0,7.0,7.0,5.0,7.0,7.0,7.0,9.0,7.0,8.0,7.0,1.0,8.0,1.0,2.0,20.0,20.0,20.0,20.0,10.0,10.0,30.0,10.0,15.0,30.0,5.0,10.0,7.0,8.0,9.0,7.0,8.0
5,21.0,2.0,8.0,1.0,86340.0,2.0,4.0,1.0,1.000000,7.0,4.0,7.0,7.0,6.0,8.0,6.0,6.0,8.0,6.0,8.0,6.0,6.0,3.0,7.0,8.0,3.0,7.0,10.0,20.0,5.0,25.0,25.0,10.0,15.0,50.0,10.0,10.0,20.0,5.0,5.0,6.0,3.0,6.0,10.0,8.0

In [185]:
feature_df.iloc[0, :].values

array([  2.10000000e+01,   4.00000000e+00,   2.00000000e+00,
         4.00000000e+00,   6.94870000e+04,   2.00000000e+00,
         7.00000000e+00,   1.00000000e+00,   5.25046382e+00,
         9.00000000e+00,   2.00000000e+00,   8.00000000e+00,
         9.00000000e+00,   1.00000000e+00,   1.00000000e+00,
         5.00000000e+00,   1.00000000e+00,   5.00000000e+00,
         6.00000000e+00,   9.00000000e+00,   1.00000000e+00,
         1.00000000e+01,   1.00000000e+01,   9.00000000e+00,
         8.00000000e+00,   1.00000000e+00,   3.00000000e+00,
         2.00000000e+00,   1.50000000e+01,   2.00000000e+01,
         2.00000000e+01,   1.50000000e+01,   1.50000000e+01,
         1.50000000e+01,   3.50000000e+01,   2.00000000e+01,
         1.50000000e+01,   2.00000000e+01,   5.00000000e+00,
         5.00000000e+00,   6.00000000e+00,   8.00000000e+00,
         8.00000000e+00,   8.00000000e+00,   7.00000000e+00])

In [246]:
### build network

pe_a = tf.placeholder(tf.float32, shape=[None, len(feature_df.columns)])
pe_b = tf.placeholder(tf.float32, shape=[None, len(feature_df.columns)])
dropout = tf.placeholder(tf.float32)

inputs_ab = tf.concat([pe_a, pe_b], 1)
inputs_ba = tf.concat([pe_b, pe_a], 1)
labels = tf.placeholder(tf.float32, shape=[None, 1])

In [205]:
input_len = inputs.get_shape()[1].value
hidden_1_len = 60
hidden_2_len = 10
output_count = 1

In [193]:
def add_layer(x_tensor, weights, biases):
    output = tf.matmul(x_tensor, weights) + biases
    output = tf.nn.relu(output)
    return output

In [206]:
weights = {
    "fc1": tf.Variable(tf.truncated_normal([input_len, hidden_1_len])),
    "fc2": tf.Variable(tf.truncated_normal([hidden_1_len, hidden_2_len])),
    "fc3": tf.Variable(tf.truncated_normal([hidden_2_len, output_count])),
}
biases = {
    "b1": tf.Variable(tf.zeros(hidden_1_len)),
    "b2": tf.Variable(tf.zeros(hidden_2_len)),
    "b3": tf.Variable(tf.zeros(output_count)),
}

In [247]:
hidden_1_layer_ab = add_layer(inputs_ab, weights["fc1"], biases["b1"])
hidden_2_layer_ab = add_layer(hidden_1_layer_ab, weights["fc2"], biases["b2"])
hidden_2_layer_ab = tf.nn.dropout(hidden_2_layer_ab, keep_prob=dropout)

hidden_1_layer_ba = add_layer(inputs_ba, weights["fc1"], biases["b1"])
hidden_2_layer_ba = add_layer(hidden_1_layer_ba, weights["fc2"], biases["b2"])
hidden_2_layer_ba = tf.nn.dropout(hidden_2_layer_ba, keep_prob=dropout)


digits = tf.matmul(hidden_2_layer_ab, weights["fc3"]) + tf.matmul(hidden_2_layer_ba, weights["fc3"]) + biases["b3"]

In [225]:
n_epochs = 10
learning_rate = 1
cost = tf.nn.sigmoid_cross_entropy_with_logits(labels=labels, logits=digits)
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

In [256]:
train_pair = train_data.loc[0:10, ['iid', 'pid']].values

for [iid, pid] in train_pair:
    print(iid, pid)

1.0 11.0
1.0 12.0
1.0 13.0
1.0 14.0
1.0 15.0
1.0 16.0
1.0 17.0
1.0 18.0
1.0 19.0
1.0 20.0
2.0 11.0

In [261]:
def get_profile(iid):
    return feature_df.loc[iid, :].values

def gen_profile(match_pair):
    iids, pids = [], []
    for [iid, pid] in match_pair:
        iids.append(get_profile(iid))
        pids.append(get_profile(pid))
    return np.array(iids), np.array(pids)


iids, pids = gen_profile(train_data.loc[0:10, ['iid', 'pid']].values)
print(iids.shape)
print(pids.shape)

(11, 45)
(11, 45)

In [262]:
cost_record = []
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(n_epochs):
        cv_index = random.randint(0, batch_count)
        for j in range(batch_count):
            if j == cv_index:
                continue;
            iids, pids = gen_profile(train_data.iloc[j:j+batch_size, ['iid', 'pid']].values)
            sess.run(optimizer, feed_dict={
                    pe_a:iids,
                    pe_b:pids,
                    dropout:0.5
                })

ValueError: too many values to unpack (expected 2)